/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './ng2-image-map-editor.directive';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/forms/src/directives/control_value_accessor';
import * as import10 from '@angular/forms/src/validators';
import * as import11 from '@angular/core/src/security';
export class Wrapper_Ng2ImageMapEditorDirective {
  /*private*/ _eventHandler:Function;
  context:import0.Ng2ImageMapEditorDirective;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this._changes = {};
    this.context = new import0.Ng2ImageMapEditorDirective();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_answers(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.answers = currValue;
      this._changes['answers'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_mainImageSrc(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.mainImageSrc = currValue;
      this._changes['mainImageSrc'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  check_mainImageWidth(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.mainImageWidth = currValue;
      this._changes['mainImageWidth'] = new import1.SimpleChange(this._expr_2,currValue);
      this._expr_2 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) {
      if (changed) {
        this.context.ngOnChanges(this._changes);
        this._changes = {};
      }
      if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); }
    }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.onAnswersUpdated.subscribe(_eventHandler.bind(view,'onAnswersUpdated'))); }
  }
}
var renderType_Ng2ImageMapEditorDirective_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_Ng2ImageMapEditorDirective_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.Ng2ImageMapEditorDirective>;
  _Ng2ImageMapEditorDirective_0_3:Wrapper_Ng2ImageMapEditorDirective;
  __NG_VALUE_ACCESSOR_0_4:any[];
  __NG_VALIDATORS_0_5:any[];
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Ng2ImageMapEditorDirective_Host0,renderType_Ng2ImageMapEditorDirective_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_0_4():any[] {
    if ((this.__NG_VALUE_ACCESSOR_0_4 == null)) { (this.__NG_VALUE_ACCESSOR_0_4 = [this._Ng2ImageMapEditorDirective_0_3.context]); }
    return this.__NG_VALUE_ACCESSOR_0_4;
  }
  get _NG_VALIDATORS_0_5():any[] {
    if ((this.__NG_VALIDATORS_0_5 == null)) { (this.__NG_VALIDATORS_0_5 = [this._Ng2ImageMapEditorDirective_0_3.context]); }
    return this.__NG_VALIDATORS_0_5;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'div',new import3.InlineArray2(2,'ng2-image-map-editor',''),rootSelector,(null as any));
    this.compView_0 = new View_Ng2ImageMapEditorDirective0(this.viewUtils,this,0,this._el_0);
    this._Ng2ImageMapEditorDirective_0_3 = new Wrapper_Ng2ImageMapEditorDirective();
    this.compView_0.create(this._Ng2ImageMapEditorDirective_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._Ng2ImageMapEditorDirective_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Ng2ImageMapEditorDirective) && (0 === requestNodeIndex))) { return this._Ng2ImageMapEditorDirective_0_3.context; }
    if (((token === import9.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_4; }
    if (((token === import10.NG_VALIDATORS) && (0 === requestNodeIndex))) { return this._NG_VALIDATORS_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Ng2ImageMapEditorDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._Ng2ImageMapEditorDirective_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const Ng2ImageMapEditorDirectiveNgFactory:import8.ComponentFactory<import0.Ng2ImageMapEditorDirective> = new import8.ComponentFactory<import0.Ng2ImageMapEditorDirective>('[ng2-image-map-editor]',View_Ng2ImageMapEditorDirective_Host0,import0.Ng2ImageMapEditorDirective);
const styles_Ng2ImageMapEditorDirective:any[] = ([] as any[]);
var renderType_Ng2ImageMapEditorDirective:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_Ng2ImageMapEditorDirective,{});
export class View_Ng2ImageMapEditorDirective0 extends import2.AppView<import0.Ng2ImageMapEditorDirective> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _el_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _el_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _el_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _el_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _el_105:any;
  _el_106:any;
  _text_107:any;
  _text_108:any;
  _text_109:any;
  _el_110:any;
  _el_111:any;
  _text_112:any;
  _text_113:any;
  _text_114:any;
  _text_115:any;
  _el_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _el_121:any;
  _el_122:any;
  _text_123:any;
  _text_124:any;
  _text_125:any;
  _el_126:any;
  _el_127:any;
  _text_128:any;
  _text_129:any;
  _text_130:any;
  _el_131:any;
  _el_132:any;
  _text_133:any;
  _text_134:any;
  _text_135:any;
  _el_136:any;
  _el_137:any;
  _text_138:any;
  _text_139:any;
  _text_140:any;
  _el_141:any;
  _el_142:any;
  _text_143:any;
  _text_144:any;
  _text_145:any;
  _el_146:any;
  _el_147:any;
  _text_148:any;
  _text_149:any;
  _text_150:any;
  _el_151:any;
  _el_152:any;
  _text_153:any;
  _text_154:any;
  _text_155:any;
  _text_156:any;
  _text_157:any;
  /*private*/ _expr_158:any;
  /*private*/ _expr_159:any;
  /*private*/ _expr_160:any;
  /*private*/ _expr_161:any;
  /*private*/ _expr_162:any;
  /*private*/ _expr_163:any;
  /*private*/ _expr_164:any;
  /*private*/ _expr_165:any;
  /*private*/ _expr_166:any;
  /*private*/ _expr_167:any;
  /*private*/ _expr_168:any;
  /*private*/ _expr_169:any;
  /*private*/ _expr_170:any;
  /*private*/ _expr_171:any;
  /*private*/ _expr_172:any;
  /*private*/ _expr_173:any;
  /*private*/ _expr_174:any;
  /*private*/ _expr_175:any;
  /*private*/ _expr_176:any;
  /*private*/ _expr_177:any;
  /*private*/ _expr_178:any;
  /*private*/ _expr_179:any;
  /*private*/ _expr_180:any;
  /*private*/ _expr_181:any;
  /*private*/ _expr_182:any;
  /*private*/ _expr_183:any;
  /*private*/ _expr_184:any;
  /*private*/ _expr_185:any;
  /*private*/ _expr_186:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Ng2ImageMapEditorDirective0,renderType_Ng2ImageMapEditorDirective,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_158 = import1.UNINITIALIZED;
    this._expr_159 = import1.UNINITIALIZED;
    this._expr_160 = import1.UNINITIALIZED;
    this._expr_161 = import1.UNINITIALIZED;
    this._expr_162 = import1.UNINITIALIZED;
    this._expr_163 = import1.UNINITIALIZED;
    this._expr_164 = import1.UNINITIALIZED;
    this._expr_165 = import1.UNINITIALIZED;
    this._expr_166 = import1.UNINITIALIZED;
    this._expr_167 = import1.UNINITIALIZED;
    this._expr_168 = import1.UNINITIALIZED;
    this._expr_169 = import1.UNINITIALIZED;
    this._expr_170 = import1.UNINITIALIZED;
    this._expr_171 = import1.UNINITIALIZED;
    this._expr_172 = import1.UNINITIALIZED;
    this._expr_173 = import1.UNINITIALIZED;
    this._expr_174 = import1.UNINITIALIZED;
    this._expr_175 = import1.UNINITIALIZED;
    this._expr_176 = import1.UNINITIALIZED;
    this._expr_177 = import1.UNINITIALIZED;
    this._expr_178 = import1.UNINITIALIZED;
    this._expr_179 = import1.UNINITIALIZED;
    this._expr_180 = import1.UNINITIALIZED;
    this._expr_181 = import1.UNINITIALIZED;
    this._expr_182 = import1.UNINITIALIZED;
    this._expr_183 = import1.UNINITIALIZED;
    this._expr_184 = import1.UNINITIALIZED;
    this._expr_185 = import1.UNINITIALIZED;
    this._expr_186 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'id','wrapper'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'header',new import3.InlineArray2(2,'id','header'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'nav',new import3.InlineArray4(4,'class','clearfix','id','nav'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'ul',new import3.InlineArray2(2,'class','float-left'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'li',new import3.InlineArray2(2,'id','to_html'),(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_8,'a',new import3.InlineArray4(4,'class','btn-success btn','href','#'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_12,'a',new import3.InlineArray4(4,'href','#','id','rectangle'),(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_13,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'a',new import3.InlineArray4(4,'href','#','id','circle'),(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_17,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_6,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_20,'a',new import3.InlineArray4(4,'href','#','id','polygon'),(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_21,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_24 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_4,'ul',new import3.InlineArray2(2,'class','float-right'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_25,'li',new import3.InlineArray4(4,'class','btn','id','edit'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_27,'a',new import3.InlineArray4(4,'class','btn','href','#'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n                    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_29,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa'),(null as any));
    this._text_32 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_25,'li',new import3.InlineArray4(4,'class','btn','id','clear'),(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_35,'a',new import3.InlineArray4(4,'class','btn btn-default','href','#'),(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_36,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-eraser'),(null as any));
    this._text_38 = this.renderer.createText(this._el_36,'',(null as any));
    this._text_39 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_25,'li',new import3.InlineArray4(4,'class','btn','id','show_help'),(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_40,'a',new import3.InlineArray2(2,'href','#'),(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_41,'i',new import3.InlineArray4(4,'aria-hidden','true','class','fa fa-question-circle'),(null as any));
    this._text_43 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._text_44 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_45 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'id','coords'),(null as any));
    this._text_47 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'id','debug'),(null as any));
    this._text_49 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'id','image_wrapper'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'div',new import3.InlineArray2(2,'id','image'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_53,'img',new import3.InlineArray8(6,'alt','#','id','img','src',''),(null as any));
    this._text_56 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_53,':svg:svg',new import3.InlineArray8(8,'baseProfile','tiny','id','svg','version','1.2','xmlns','http://www.w3.org/2000/svg'),(null as any));
    this._text_58 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._text_59 = this.renderer.createText(this._el_51,'\n    ',(null as any));
    this._text_60 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_61 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'id','from_html_wrapper'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n    ',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'form',new import3.InlineArray2(2,'id','from_html_form'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n        ',(null as any));
    this._el_67 = import3.createRenderElement(this.renderer,this._el_65,'h5',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'Loading areas',(null as any));
    this._text_69 = this.renderer.createText(this._el_65,'\n        ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_65,'span',new import3.InlineArray4(4,'class','close_button','title','close'),(null as any));
    this._text_71 = this.renderer.createText(this._el_65,'\n        ',(null as any));
    this._el_72 = import3.createRenderElement(this.renderer,this._el_65,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n            ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_72,'label',new import3.InlineArray2(2,'for','code_input'),(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'Enter your html code:',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'\n            ',(null as any));
    this._el_77 = import3.createRenderElement(this.renderer,this._el_72,'textarea',new import3.InlineArray2(2,'id','code_input'),(null as any));
    this._text_78 = this.renderer.createText(this._el_72,'\n        ',(null as any));
    this._text_79 = this.renderer.createText(this._el_65,'\n        ',(null as any));
    this._el_80 = import3.createRenderElement(this.renderer,this._el_65,'button',new import3.InlineArray2(2,'id','load_code_button'),(null as any));
    this._text_81 = this.renderer.createText(this._el_80,'Load',(null as any));
    this._text_82 = this.renderer.createText(this._el_65,'\n    ',(null as any));
    this._text_83 = this.renderer.createText(this._el_63,'\n',(null as any));
    this._text_84 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_85 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_86 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_87 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'id','overlay'),(null as any));
    this._text_88 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_89 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'id','help'),(null as any));
    this._text_90 = this.renderer.createText(this._el_89,'\n    ',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_89,'span',new import3.InlineArray4(4,'class','close_button','title','close'),(null as any));
    this._text_92 = this.renderer.createText(this._el_89,'\n    ',(null as any));
    this._el_93 = import3.createRenderElement(this.renderer,this._el_89,'div',new import3.InlineArray2(2,'class','txt'),(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'\n        ',(null as any));
    this._el_95 = import3.createRenderElement(this.renderer,this._el_93,'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_96 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_95,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'',(null as any));
    this._text_99 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_95,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_101 = import3.createRenderElement(this.renderer,this._el_100,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'ENTER',(null as any));
    this._text_103 = this.renderer.createText(this._el_100,'',(null as any));
    this._text_104 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_105 = import3.createRenderElement(this.renderer,this._el_95,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_106 = import3.createRenderElement(this.renderer,this._el_105,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_107 = this.renderer.createText(this._el_106,'ESC',(null as any));
    this._text_108 = this.renderer.createText(this._el_105,'',(null as any));
    this._text_109 = this.renderer.createText(this._el_95,'\n            ',(null as any));
    this._el_110 = import3.createRenderElement(this.renderer,this._el_95,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_111 = import3.createRenderElement(this.renderer,this._el_110,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_112 = this.renderer.createText(this._el_111,'SHIFT',(null as any));
    this._text_113 = this.renderer.createText(this._el_110,'',(null as any));
    this._text_114 = this.renderer.createText(this._el_95,'\n        ',(null as any));
    this._text_115 = this.renderer.createText(this._el_93,'\n        ',(null as any));
    this._el_116 = import3.createRenderElement(this.renderer,this._el_93,'section',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_117 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_118 = import3.createRenderElement(this.renderer,this._el_116,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_119 = this.renderer.createText(this._el_118,'',(null as any));
    this._text_120 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_121 = import3.createRenderElement(this.renderer,this._el_116,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_122 = import3.createRenderElement(this.renderer,this._el_121,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'DELETE',(null as any));
    this._text_124 = this.renderer.createText(this._el_121,'',(null as any));
    this._text_125 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_126 = import3.createRenderElement(this.renderer,this._el_116,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_127 = import3.createRenderElement(this.renderer,this._el_126,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_128 = this.renderer.createText(this._el_127,'ESC',(null as any));
    this._text_129 = this.renderer.createText(this._el_126,'',(null as any));
    this._text_130 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_131 = import3.createRenderElement(this.renderer,this._el_116,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_132 = import3.createRenderElement(this.renderer,this._el_131,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_133 = this.renderer.createText(this._el_132,'SHIFT',(null as any));
    this._text_134 = this.renderer.createText(this._el_131,'',(null as any));
    this._text_135 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_136 = import3.createRenderElement(this.renderer,this._el_116,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_137 = import3.createRenderElement(this.renderer,this._el_136,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_138 = this.renderer.createText(this._el_137,'↑',(null as any));
    this._text_139 = this.renderer.createText(this._el_136,'',(null as any));
    this._text_140 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_141 = import3.createRenderElement(this.renderer,this._el_116,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_142 = import3.createRenderElement(this.renderer,this._el_141,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_143 = this.renderer.createText(this._el_142,'↓',(null as any));
    this._text_144 = this.renderer.createText(this._el_141,'',(null as any));
    this._text_145 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_146 = import3.createRenderElement(this.renderer,this._el_116,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_147 = import3.createRenderElement(this.renderer,this._el_146,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_148 = this.renderer.createText(this._el_147,'←',(null as any));
    this._text_149 = this.renderer.createText(this._el_146,'',(null as any));
    this._text_150 = this.renderer.createText(this._el_116,'\n            ',(null as any));
    this._el_151 = import3.createRenderElement(this.renderer,this._el_116,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_152 = import3.createRenderElement(this.renderer,this._el_151,'span',new import3.InlineArray2(2,'class','key'),(null as any));
    this._text_153 = this.renderer.createText(this._el_152,'→',(null as any));
    this._text_154 = this.renderer.createText(this._el_151,'',(null as any));
    this._text_155 = this.renderer.createText(this._el_116,'\n        ',(null as any));
    this._text_156 = this.renderer.createText(this._el_93,'\n    ',(null as any));
    this._text_157 = this.renderer.createText(this._el_89,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._el_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._el_105,
      this._el_106,
      this._text_107,
      this._text_108,
      this._text_109,
      this._el_110,
      this._el_111,
      this._text_112,
      this._text_113,
      this._text_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._el_121,
      this._el_122,
      this._text_123,
      this._text_124,
      this._text_125,
      this._el_126,
      this._el_127,
      this._text_128,
      this._text_129,
      this._text_130,
      this._el_131,
      this._el_132,
      this._text_133,
      this._text_134,
      this._text_135,
      this._el_136,
      this._el_137,
      this._text_138,
      this._text_139,
      this._text_140,
      this._el_141,
      this._el_142,
      this._text_143,
      this._text_144,
      this._text_145,
      this._el_146,
      this._el_147,
      this._text_148,
      this._text_149,
      this._text_150,
      this._el_151,
      this._el_152,
      this._text_153,
      this._text_154,
      this._text_155,
      this._text_156,
      this._text_157
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_158:boolean = !this.context.valid;
    if (import3.checkBinding(throwOnChange,this._expr_158,currVal_158)) {
      this.renderer.setElementClass(this._el_9,'btn-success',currVal_158);
      this._expr_158 = currVal_158;
    }
    const currVal_159:any = import3.inlineInterpolate(1,'',this.context.labels.save_answers,'');
    if (import3.checkBinding(throwOnChange,this._expr_159,currVal_159)) {
      this.renderer.setText(this._text_10,currVal_159);
      this._expr_159 = currVal_159;
    }
    const currVal_160:any = (this.context.currentType == 'rectangle');
    if (import3.checkBinding(throwOnChange,this._expr_160,currVal_160)) {
      this.renderer.setElementClass(this._el_13,'btn-default',currVal_160);
      this._expr_160 = currVal_160;
    }
    const currVal_161:any = (this.context.currentType != 'rectangle');
    if (import3.checkBinding(throwOnChange,this._expr_161,currVal_161)) {
      this.renderer.setElementClass(this._el_13,'btn',currVal_161);
      this._expr_161 = currVal_161;
    }
    const currVal_162:any = this.context.icons.rectangle;
    if (import3.checkBinding(throwOnChange,this._expr_162,currVal_162)) {
      this.renderer.setElementProperty(this._el_14,'src',this.viewUtils.sanitizer.sanitize(import11.SecurityContext.URL,currVal_162));
      this._expr_162 = currVal_162;
    }
    const currVal_163:any = (this.context.currentType == 'circle');
    if (import3.checkBinding(throwOnChange,this._expr_163,currVal_163)) {
      this.renderer.setElementClass(this._el_17,'btn-default',currVal_163);
      this._expr_163 = currVal_163;
    }
    const currVal_164:any = (this.context.currentType != 'circle');
    if (import3.checkBinding(throwOnChange,this._expr_164,currVal_164)) {
      this.renderer.setElementClass(this._el_17,'btn',currVal_164);
      this._expr_164 = currVal_164;
    }
    const currVal_165:any = this.context.icons.circle;
    if (import3.checkBinding(throwOnChange,this._expr_165,currVal_165)) {
      this.renderer.setElementProperty(this._el_18,'src',this.viewUtils.sanitizer.sanitize(import11.SecurityContext.URL,currVal_165));
      this._expr_165 = currVal_165;
    }
    const currVal_166:any = (this.context.currentType == 'polygon');
    if (import3.checkBinding(throwOnChange,this._expr_166,currVal_166)) {
      this.renderer.setElementClass(this._el_21,'btn-default',currVal_166);
      this._expr_166 = currVal_166;
    }
    const currVal_167:any = (this.context.currentType != 'polygon');
    if (import3.checkBinding(throwOnChange,this._expr_167,currVal_167)) {
      this.renderer.setElementClass(this._el_21,'btn',currVal_167);
      this._expr_167 = currVal_167;
    }
    const currVal_168:any = this.context.icons.polygon;
    if (import3.checkBinding(throwOnChange,this._expr_168,currVal_168)) {
      this.renderer.setElementProperty(this._el_22,'src',this.viewUtils.sanitizer.sanitize(import11.SecurityContext.URL,currVal_168));
      this._expr_168 = currVal_168;
    }
    const currVal_169:any = this.context.isEditMode;
    if (import3.checkBinding(throwOnChange,this._expr_169,currVal_169)) {
      this.renderer.setElementClass(this._el_29,'btn-primary',currVal_169);
      this._expr_169 = currVal_169;
    }
    const currVal_170:boolean = !this.context.isEditMode;
    if (import3.checkBinding(throwOnChange,this._expr_170,currVal_170)) {
      this.renderer.setElementClass(this._el_29,'btn-default',currVal_170);
      this._expr_170 = currVal_170;
    }
    const currVal_171:any = this.context.isEditMode;
    if (import3.checkBinding(throwOnChange,this._expr_171,currVal_171)) {
      this.renderer.setElementClass(this._el_31,'fa-toggle-on',currVal_171);
      this._expr_171 = currVal_171;
    }
    const currVal_172:boolean = !this.context.isEditMode;
    if (import3.checkBinding(throwOnChange,this._expr_172,currVal_172)) {
      this.renderer.setElementClass(this._el_31,'fa-toggle-off',currVal_172);
      this._expr_172 = currVal_172;
    }
    const currVal_173:any = import3.inlineInterpolate(1,' ',this.context.labels.edit,'');
    if (import3.checkBinding(throwOnChange,this._expr_173,currVal_173)) {
      this.renderer.setText(this._text_32,currVal_173);
      this._expr_173 = currVal_173;
    }
    const currVal_174:any = import3.inlineInterpolate(1,' ',this.context.labels.clear,'');
    if (import3.checkBinding(throwOnChange,this._expr_174,currVal_174)) {
      this.renderer.setText(this._text_38,currVal_174);
      this._expr_174 = currVal_174;
    }
    const currVal_175:any = import3.inlineInterpolate(1,'',this.context.labels.drawing_mode,'');
    if (import3.checkBinding(throwOnChange,this._expr_175,currVal_175)) {
      this.renderer.setText(this._text_98,currVal_175);
      this._expr_175 = currVal_175;
    }
    const currVal_176:any = import3.inlineInterpolate(1,' — ',this.context.labels.drawing_mode_enter,'');
    if (import3.checkBinding(throwOnChange,this._expr_176,currVal_176)) {
      this.renderer.setText(this._text_103,currVal_176);
      this._expr_176 = currVal_176;
    }
    const currVal_177:any = import3.inlineInterpolate(1,' — ',this.context.labels.drawing_mode_esc,'');
    if (import3.checkBinding(throwOnChange,this._expr_177,currVal_177)) {
      this.renderer.setText(this._text_108,currVal_177);
      this._expr_177 = currVal_177;
    }
    const currVal_178:any = import3.inlineInterpolate(1,' — ',this.context.labels.drawing_mode_shift,'');
    if (import3.checkBinding(throwOnChange,this._expr_178,currVal_178)) {
      this.renderer.setText(this._text_113,currVal_178);
      this._expr_178 = currVal_178;
    }
    const currVal_179:any = import3.inlineInterpolate(1,'',this.context.labels.editing_mode,'');
    if (import3.checkBinding(throwOnChange,this._expr_179,currVal_179)) {
      this.renderer.setText(this._text_119,currVal_179);
      this._expr_179 = currVal_179;
    }
    const currVal_180:any = import3.inlineInterpolate(1,' — ',this.context.labels.editing_mode_delete,'');
    if (import3.checkBinding(throwOnChange,this._expr_180,currVal_180)) {
      this.renderer.setText(this._text_124,currVal_180);
      this._expr_180 = currVal_180;
    }
    const currVal_181:any = import3.inlineInterpolate(1,' — ',this.context.labels.editing_mode_esc,'');
    if (import3.checkBinding(throwOnChange,this._expr_181,currVal_181)) {
      this.renderer.setText(this._text_129,currVal_181);
      this._expr_181 = currVal_181;
    }
    const currVal_182:any = import3.inlineInterpolate(1,' — ',this.context.labels.editing_mode_shift,'');
    if (import3.checkBinding(throwOnChange,this._expr_182,currVal_182)) {
      this.renderer.setText(this._text_134,currVal_182);
      this._expr_182 = currVal_182;
    }
    const currVal_183:any = import3.inlineInterpolate(1,' — ',this.context.labels.editing_mode_up,'');
    if (import3.checkBinding(throwOnChange,this._expr_183,currVal_183)) {
      this.renderer.setText(this._text_139,currVal_183);
      this._expr_183 = currVal_183;
    }
    const currVal_184:any = import3.inlineInterpolate(1,' — ',this.context.labels.editing_mode_down,'');
    if (import3.checkBinding(throwOnChange,this._expr_184,currVal_184)) {
      this.renderer.setText(this._text_144,currVal_184);
      this._expr_184 = currVal_184;
    }
    const currVal_185:any = import3.inlineInterpolate(1,' — ',this.context.labels.editing_mode_left,'');
    if (import3.checkBinding(throwOnChange,this._expr_185,currVal_185)) {
      this.renderer.setText(this._text_149,currVal_185);
      this._expr_185 = currVal_185;
    }
    const currVal_186:any = import3.inlineInterpolate(1,' — ',this.context.labels.editing_mode_right,'');
    if (import3.checkBinding(throwOnChange,this._expr_186,currVal_186)) {
      this.renderer.setText(this._text_154,currVal_186);
      this._expr_186 = currVal_186;
    }
  }
}