/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ng2-image-map-editor.module';
import * as import2 from '@angular/core/src/di/injector';
class Ng2ImageMapEditorModuleInjector extends import0.NgModuleInjector<import1.Ng2ImageMapEditorModule> {
  _Ng2ImageMapEditorModule_0:import1.Ng2ImageMapEditorModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.Ng2ImageMapEditorModule {
    this._Ng2ImageMapEditorModule_0 = new import1.Ng2ImageMapEditorModule();
    return this._Ng2ImageMapEditorModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Ng2ImageMapEditorModule)) { return this._Ng2ImageMapEditorModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2ImageMapEditorModuleNgFactory:import0.NgModuleFactory<import1.Ng2ImageMapEditorModule> = new import0.NgModuleFactory(Ng2ImageMapEditorModuleInjector,import1.Ng2ImageMapEditorModule);